apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dashboard-reader-bind
subjects:
- kind: ServiceAccount # pode ser usuario, grupo, etc...
  name: user-dashboard
  namespace: default
roleRef:
  kind: Role
  name: dashboard-reader
  apiGroup: rbac.authorization.k8s.io