apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dashboard-reader
rules:
- apiGroups:
    - ""
    - "apps"
  resources:
    - pods
    - services
    - deployments
  verbs:
    - get
    - list
    - watch