NAME: minha-api
LAST DEPLOYED: Fri Sep  8 18:49:07 2023
NAMESPACE: default
STATUS: pending-install
REVISION: 1
TEST SUITE: None
USER-SUPPLIED VALUES:
{}

COMPUTED VALUES:
api:
  image: fabricioveronez/pedelogo-catalogo:v1
  ingress:
  - 127.0.0.1.nip.io
  serviceType: ClusterIP
mongodb:
  credentials:
    database: admin
    password: mongopwd
    username: mongouser
  tag: 4.2.8

HOOKS:
MANIFEST:
---
# Source: api-produto/templates/mongodb-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: minha-api-mongodb-secret
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: "bW9uZ291c2Vy"
  MONGO_INITDB_ROOT_PASSWORD: "bW9uZ29wd2Q="
---
# Source: api-produto/templates/api-configmap.yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: minha-api-api-configmap
  namespace: default
data:
    Mongo__Host: minha-api-mongo-service
    Mongo__DataBase: admin
---
# Source: api-produto/templates/api-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: minha-api-api-service
spec:
  selector:
    app: minha-api-api
  ports:
  - port: 80
    targetPort: 80
    # nodePort: 30000
  type: ClusterIP
---
# Source: api-produto/templates/mongodb-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: minha-api-mongo-service
spec:
  selector:
    app: minha-api-mongodb
  ports:
  - port: 27017
    targetPort: 27017
---
# Source: api-produto/templates/api-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minha-api-api-deployment
spec:
  selector:
    matchLabels:
      app: minha-api-api
  template: 
    metadata:          
      labels:
        app: minha-api-api
    spec:            
      containers:
      - name: api
        image: fabricioveronez/pedelogo-catalogo:v1
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        resources: {}
        env:
        - name: Mongo__User
          valueFrom:
            secretKeyRef:
              key: MONGO_INITDB_ROOT_USERNAME
              name: minha-api-mongodb-secret
        - name: Mongo__Password
          valueFrom:
            secretKeyRef:
              key: MONGO_INITDB_ROOT_PASSWORD
              name: minha-api-mongodb-secret
        envFrom:
        - configMapRef:
            name: minha-api-api-configmap
---
# Source: api-produto/templates/mongodb-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minha-api-mongodb-deployment
spec:
  selector:
    matchLabels:
      app: minha-api-mongodb
  template:
    metadata:     
      labels:
        app: minha-api-mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:4.2.8
        ports:
        - containerPort: 27017
        resources: {}
        envFrom:
        - secretRef:
            name: minha-api-mongodb-secret
---
# Source: api-produto/templates/api-ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minha-api-api-ingress
  labels:
    app: minha-api-api-ingress
    chart: "api-produto-0.1.0"
    release: "minha-api"
    heritage: "Helm"
spec:
  ingressClassName: nginx
  rules:
    - host: 127.0.0.1.nip.io
      http:
        paths:
        - path: "/"
          pathType: Prefix
          backend:
            service:
                name: minha-api-api-service
                port: 
                    number: 80

NOTES:
# Instalado

# testar if
# helm install minha-api  ./helm/api-produto --set mongodb.existSecret=umsecret --dry-run --debug > ./helm/api-produto/output.yml
