NAME: minha-api
LAST DEPLOYED: Mon Sep 11 14:46:31 2023
NAMESPACE: default
STATUS: pending-install
REVISION: 1
TEST SUITE: None
USER-SUPPLIED VALUES:
{}

COMPUTED VALUES:
api:
  image: fabricioveronez/pedelogo-catalogo:v1
  ingress:
  - 127.0.0.1.nip.io
  serviceType: ClusterIP
mongodb:
  auth:
    database: produto
    password: mongopwd
    rootPassword: mongoRoot
    username: mongouser
  persistence:
    enabled: true

HOOKS:
MANIFEST:
---
# Source: api-produto/templates/api-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: minha-api-api-secret
type: Opaque
data:
  Mongo__User: "bW9uZ291c2Vy"
  Mongo__Password: "bW9uZ29wd2Q="
---
# Source: api-produto/templates/api-configmap.yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: minha-api-api-configmap
  namespace: default
data:
    Mongo__Host: minha-api-mongodb
    Mongo__DataBase: produto
---
# Source: api-produto/templates/api-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: minha-api-api-service
spec:
  selector:
    app: minha-api-api
  ports:
  - port: 80
    targetPort: 80
    # nodePort: 30000
  type: ClusterIP
---
# Source: api-produto/templates/api-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minha-api-api-deployment
spec:
  selector:
    matchLabels:
      app: minha-api-api
  template: 
    metadata:          
      labels:
        app: minha-api-api
    spec:            
      containers:
      - name: api
        image: fabricioveronez/pedelogo-catalogo:v1
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        resources: {}
        envFrom:
        - configMapRef:
            name: minha-api-api-configmap
        - secretRef:
            name: minha-api-api-secret
---
# Source: api-produto/templates/api-ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minha-api-api-ingress
  labels:
    app: minha-api-api-ingress
    chart: "api-produto-0.1.0"
    release: "minha-api"
    heritage: "Helm"
spec:
  ingressClassName: nginx
  rules:
    - host: 127.0.0.1.nip.io
      http:
        paths:
        - path: "/"
          pathType: Prefix
          backend:
            service:
                name: minha-api-api-service
                port: 
                    number: 80

NOTES:
A release minha-api foi criada com sucesso!

# testar if
# helm install minha-api  ./helm/api-produto --set mongodb.existSecret=umsecret --dry-run --debug > ./helm/api-produto/output.yml

# instalar o mongodb via chart da bitnami
helm install my-release-mongodb oci://registry-1.docker.io/bitnamicharts/mongodb
