apiVersion: batch/v1
kind: Job
metadata:
  name: roleta-job
spec:
  backoffLimit: 20
  parallelism: 2
  completions: 3
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: job
        image: kubedevio/roleta
        args: ["-c",  "4", "-m", "5"]
      restartPolicy: Never
