apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
        - name: init
          image: kubedevio/ubuntu-curl:v1
          command:
            - "curl"
            - "-X"
            - "GET"
            - "https://jsonplaceholder.typicode.com/comments"
      containers:
      - name: nginx
        image: nginx
        lifecycle:
          postStart:
            exec:
              command:
                - "curl"
                - "-X"
                - "GET"
                - "https://jsonplaceholder.typicode.com/photos"
          preStop:
            exec:
              command:
                - "curl"
                - "-X"
                - "GET"
                - "https://jsonplaceholder.typicode.com/posts/1/comments"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
