apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-versao
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1 # quantos pods a mais eu posso criar, pode ser em porcentagem tbm
      maxUnavailable: 1 # quantos a menos
  replicas: 10
  selector:
    matchLabels:
      app: api-versao
  template:
    metadata:
      labels:
        app: api-versao
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      containers:
      - name: api-versao
        image: kubedevio/api-versao:v2
        resources: {}
        ports:
        - containerPort: 8080
