apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      nodeSelector:
        database: mongodb
      containers:
      - name: mongodb-pod
        image: mongo:4.2.8
        ports:
          - containerPort: 27017
        resources: {}
        envFrom:
          - secretRef:
              name: mongodb-secret
        volumeMounts:
          - mountPath: /data/db
            name: mongo-data
      volumes:
        - name: mongo-data
          hostPath:
            path: /volumes/mongodb
