apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-deployment
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: resource-container
  minReplicas: 1
  maxReplicas: 20
  # targetCPUUtilizationPercentage: 50 # quando apiVersion for autoscaling/v1

  # quando apiVersion for autoscaling/v2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
        
