apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        startupProbe:
          httpGet:
            path: /health
            port: 80
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 3
          timeoutSeconds: 1
          failureThreshold: 30
        readinessProbe:
          httpGet:
            path: /read
            port: 80
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 3
          timeoutSeconds: 1
          failureThreshold: 1
        livenessProbe:
          httpGet:
            # host: localhost
            path: /health
            port: 80
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 3
          timeoutSeconds: 1
          failureThreshold: 1
        image: welissonoliveira/pedelogo-catalogo:v1.0.0
        resources:
          requests:
            memory: "40Mi"
            cpu: "3m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: api-configmap
        env:
          - name: Mongo__User
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: MONGO_INITDB_ROOT_USERNAME
          - name: Mongo__Password
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: MONGO_INITDB_ROOT_PASSWORD

