kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-api-configmap
  namespace: default
data:
    Mongo__Host: {{template "mongodb.serviceName" . }}
    Mongo__DataBase: {{ .Values.mongodb.credentials.database }}