apiVersion: v1
kind: LimitRange
metadata:
  name: limit-container
spec:
  limits:
    - max:
        cpu: "800m"
        memory: 900Mi
      min:
        cpu: "150m"
        memory: 100Mi
      default:
        cpu: "250m"
        memory: "128Mi"
      defaultRequest:
        cpu: "150m"
        memory: "110Mi"
      type: Container